Hashtag/Hashtag.Webapi/Controllers/CategoryController.cs
using System.Web.Mvc;
using Hashtag.Webapi.Services;
using Hashtag.Webapi.Services.Implementation;

namespace Hashtag.Webapi.Controllers
{
    public sealed class CategoryController : Controller
    {

        private readonly ICategoryService categoryService;

        public CategoryController() : this(new CategoryService())
        {

        }

        public CategoryController(ICategoryService categoryService)
        {
            this.categoryService = categoryService;
        }

        public ActionResult List()
        {
            var categories = categoryService.GetAllCategories();
            return PartialView("List", categories);
        }
    }
}

Hashtag/Hashtag.Webapi/Controllers/EventController.cs
using System.Web.Mvc;
using Hashtag.Webapi.Services;
using Hashtag.Webapi.Services.Implementation;
using System.Threading.Tasks;
using Facebook;
using Newtonsoft.Json.Linq;

namespace Hashtag.Webapi.Controllers
{
    public class EventController : Controller
    {
        private readonly IEventService eventService;
        private readonly ITrackerService trackerService;

        public EventController() : this(new EventService(), new TrackerService())
        {

        }

        public EventController(IEventService eventService, ITrackerService trackerService)
        {
            this.eventService = eventService;
            this.trackerService = trackerService;
        }

        public ActionResult Index()
        {
            var events = eventService.GetEventsHeadlines();
            return View(events);
        }

        public ActionResult Search(EventSearchQuery search)
        {
            var events = eventService.QueryEvents(search);
            return View("Index", events);
        }

        public ActionResult Details(int id)
        {
            var eventItem = eventService.GetEventDetails(id);
            this.trackerService.AddEventToUserInterests(id);

            return View(eventItem);
        }
    }
}

Hashtag/Hashtag.Webapi/Controllers/api/EventController.cs
using Models;

namespace Hashtag.Webapi.Controllers.api
{
    using System.Web.Http;
    using Services;
    using Services.Implementation;

    [RoutePrefix("api/Event")]
    public sealed class EventController : ApiController
    {
        private readonly IEventService eventService;
        private readonly ITrackerService trackerService;

        public EventController() : this(new EventService(), new TrackerService())
        {

        }

        public EventController(IEventService eventService,ITrackerService trackerService)
        {
            this.eventService = eventService;
            this.trackerService = trackerService;
        }

        [Route("get")]
        public IHttpActionResult Get()
        {
            var events = eventService.GetEventsHeadlines();
            return Ok(events);
        }

        [Route("get")]
        public IHttpActionResult Get(int id)
        {
            var eventdetails = this.eventService.GetEventDetails(id);
            this.trackerService.AddEventToUserInterests(id);
       
            return Ok(eventdetails);
        }

        [Route("get/category/{id}")]
        [HttpGet]
        public IHttpActionResult EventsInCategory(int id)
        {
            var eventdetails = this.eventService.EventsInCategory(id);
            return Ok(eventdetails);
        }

    }
}

Hashtag/Hashtag.Webapi/Views/Event/Details.cshtml
@using System.Globalization
@model Models.EventEntry

@{
    ViewBag.Title = "title";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="col-md-offset-1 col-md-10">
    <div id="map" style="height: 150px;"></div>
    <h2>@Model.Title</h2>
    <img src="@Model.Image.Large" width="100%;"/>
    <h4>@Html.Raw(Model.LongDescription)</h4>
    <h5>@Model.StartDate</h5>
</div>

@section scripts {
    <script type="text/javascript">

        var map;
        var mylat = { lat: @Model.Location.Lattiude.ToString(CultureInfo.CreateSpecificCulture("en-GB")), 
            lng: @Model.Location.Longitude.ToString(CultureInfo.CreateSpecificCulture("en-GB")) };
        function initMap() {
            map = new google.maps.Map(document.getElementById('map'), {
                center: mylat,
                zoom: 15
            });

            var marker = new google.maps.Marker({
                position: mylat,
                map: map,
                title: 'Hello World!'
            });
        }

    </script>

    <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD-qxzFhcfCNzmw-DjNoNMTg8kJ2XNNBN4&callback=initMap">
    </script>

}

Hashtag/Hashtag.Webapi/Views/Event/Index.cshtml

@using Models
@model SearchEntryList
@{
    ViewBag.Title = "title";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="row search-bar">
    @using (Html.BeginForm("Search", "Event", FormMethod.Get, new { @class = "form-inline" }))
    {

        <div class="form-group col-md-offset-4 col-md-5">
            <label class="col-md-2"></label>
            <div class="col-md-8">
                <input class="form-control" type="search" name="Query" placeholder="interesuje mnie" />
                <span class="fa fa-search"></span>
            </div>
        </div>
        <input class="btn btn-primary col-md-1" type="submit" value="szukaj" />
    }
</div>
<div class="row">
    <div class="col-md-3">
        @Html.Action("List", "Category")
    </div>
    <div class="col-md-9">
        @foreach (var entry in Model.EventsList)
            {
            <div class="row event-row">
                <div class="col-md-2"><img src="@entry.Image.Thumbnail" /></div>
                <div class="col-md-8">
                    <a href="@Url.Action("Details", "Event", new { id = entry.Id })">
                        <h3>@entry.Title</h3>
                    </a>
                    <h6>@entry.StartDate</h6>
                    <h6 class="indicator">
                        <i class="glyphicon glyphicon-fire">@entry.TotalCount</i><i class="glyphicon glyphicon-heart my-popover"
                                                                                    @if (entry.FriendsUrl != null && entry.FriendsCount > 0) { <text>
                                                                                    data-trigger="hover"
                                                                                    data-content="@foreach (var friendImage in entry.FriendsUrl)
                                                                                                              {
                                                                                                                  <text>
                                    <img src='@friendImage' />
                                   </text>
                                                                                                              }
                               "
                                                                                            </text>
                                                                                        }>@entry.FriendsCount</i>
                    </h6>
                    <div>
                        @foreach (var o in @entry.Categories)
                        {
                            <span class="badge">@o.alias</span>
                        }
                    </div>
                </div>
            </div>
        }
    </div>
</div>